import re
import shutil
import typing as t
from pathlib import Path

from html2image import Html2Image

from .nav import Page
from .utils import THasRender, logger, print_random_messages


RX_ABS_URL = re.compile(
    r"""(\s(?:src|href|data-[a-z0-9_-]+)\s*=\s*['"])(\/(?:[a-z0-9_-][^'"]*)?)(['"])""",
    re.IGNORECASE,
)

SOCIAL_CARD_SIZE = (1200, 630)


class DocsBuilder(THasRender if t.TYPE_CHECKING else object):
    relativize_static: bool = False
    hti: Html2Image

    def build(self) -> None:
        if self.build_folder.exists():
            shutil.rmtree(self.build_folder)
        self.build_folder.mkdir(exist_ok=True)
        self.build_folder_static.mkdir(exist_ok=True)

        logger.info("Copying static folder...")
        self._copy_static_folder()

        logger.info("Rendering pages...")
        self.md_pages = []
        self.hti = Html2Image()

        for index, url in enumerate(self.nav.pages, start=1):
            page = self.nav.get_page(url)
            if not page:
                logger.error(f"Page not found: {url}")
                continue
            self._build_page(page)
            self._build_social_card(page)

        logger.info("   ...")
        print_random_messages()
        logger.info("✨ Done! ✨")

    def _build_page(self, page: Page) -> None:
        url = page.url.strip("/")
        filename = f"{url}/index.html".lstrip("/")
        filepath = self.build_folder / filename
        folderpath = filepath.parent
        folderpath.mkdir(parents=True, exist_ok=True)

        logger.info(f"Rendering page {url}")
        html = self.render_page(page, save_content=True)

        logger.info("Relativizing page URLs")
        html = self._relativize_urls(html, filename)

        logger.info("Writing file")
        filepath.write_text(html)

    def _build_social_card(self, page: Page) -> None:
        url = page.url.strip("/")
        filename = f"{url}/og-card.html".lstrip("/")
        filepath = self.build_folder / filename
        folderpath = filepath.parent

        logger.info(f"Rendering social card for page {url}")
        html = self.render_social_card(page)
        # The static URLS must be readable without a web server
        # so the image generated by html2image is correct
        html = self._relativize_urls(html, filename, static=True)
        filepath.write_text(html)

        logger.info("Generating social card")
        self.hti.output_path = folderpath
        self.hti.screenshot(
            url=str(filepath),
            size=SOCIAL_CARD_SIZE,
            save_as="og-card.png",
        )
        filepath.unlink()

    def _copy_static_folder(self) -> None:
        shutil.copytree(
            self.static_folder,
            self.build_folder_static,
            dirs_exist_ok=True,
        )

    def _relativize_urls(
        self,
        html: str,
        filename: str = "/",
        *,
        static: bool | None = None,
    ) -> str:
        pos = 0
        static = self.relativize_static if static is None else static

        while True:
            match = RX_ABS_URL.search(html, pos=pos)
            if not match:
                break

            left, url, right = match.groups()
            if url.startswith(self.static_url):
                newurl = self._relativize_static_url(url)
                if static:
                    newurl = self._get_relative_url(newurl, filename)
            else:
                newurl = self._get_relative_url(url, filename)
                if not newurl.endswith("/"):
                    newurl = f"{newurl}/"

            logger.info(f"{url} -> {newurl}")
            pos = match.end()
            html = f"{html[:match.start()]}{left}{newurl}{right}{html[pos:]}"

        return html

    def _relativize_static_url(self, current_url: str) -> str:
        url = current_url.rsplit("?", 1)[0]

        filepath = self.build_folder_static / url.removeprefix(self.static_url).lstrip(
            "/"
        )
        if not filepath.exists():
            logger.info(f"{filepath} doesn't exists")
            self._download_url(url, filepath)

        return url

    def _download_url(self, url: str, filepath: Path) -> None:
        logger.info(f"Downloading {url}...")
        sf = self.server.application.find_file(url)
        if sf is None:
            logger.error(f"{url} doesn't exists")
            return
        src_path, _ = sf.get_path_and_headers({})
        filepath.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src_path, filepath)
        logger.info(f"Created {filepath}")

    def _get_relative_url(self, current_url: str, filename: str) -> str:
        filename = filename.removesuffix("index.html")
        depth = filename.count("/")
        url = ("../" * depth) + current_url.lstrip("/")

        if not url.startswith("."):
            url = f"./{url}"
        return url
